export const data = [
  {
    id: 1,
    first_name: 'Karlie',
    last_name: 'Bautiste',
    email: 'kbautiste0@blinklist.com',
    gender: 'Non-binary',
    ip_address: '119.100.137.65',
  },
  {
    id: 2,
    first_name: 'Bobbette',
    last_name: 'Mingasson',
    email: 'bmingasson1@stumbleupon.com',
    gender: 'Polygender',
    ip_address: '15.92.168.136',
  },
  {
    id: 3,
    first_name: 'Reagan',
    last_name: 'Hadrill',
    email: 'rhadrill2@a8.net',
    gender: 'Male',
    ip_address: '11.18.254.173',
  },
  {
    id: 4,
    first_name: 'Ephraim',
    last_name: 'MacMeanma',
    email: 'emacmeanma3@squarespace.com',
    gender: 'Female',
    ip_address: '92.88.22.181',
  },
  {
    id: 5,
    first_name: 'Tito',
    last_name: 'Giottoi',
    email: 'tgiottoi4@goo.gl',
    gender: 'Bigender',
    ip_address: '198.26.43.55',
  },
  {
    id: 6,
    first_name: 'Hasty',
    last_name: 'Solomon',
    email: 'hsolomon5@youtube.com',
    gender: 'Genderfluid',
    ip_address: '154.73.38.206',
  },
  {
    id: 7,
    first_name: 'Corny',
    last_name: 'Rabl',
    email: 'crabl6@auda.org.au',
    gender: 'Non-binary',
    ip_address: '93.15.133.249',
  },
  {
    id: 8,
    first_name: 'Tod',
    last_name: 'Keoghan',
    email: 'tkeoghan7@netscape.com',
    gender: 'Agender',
    ip_address: '226.69.206.171',
  },
  {
    id: 9,
    first_name: 'Krishnah',
    last_name: 'Duchateau',
    email: 'kduchateau8@oaic.gov.au',
    gender: 'Genderfluid',
    ip_address: '8.167.87.197',
  },
  {
    id: 10,
    first_name: 'Carver',
    last_name: "O'Mannion",
    email: 'comannion9@utexas.edu',
    gender: 'Genderqueer',
    ip_address: '71.3.14.20',
  },
];
